# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: ubuntu_16_04
    displayName: 'Build - Ubuntu 16.04'
    continueOnError: false
    pool:
      vmImage: 'Ubuntu 16.04'
    workspace:
      clean: all
    steps:
      - script: |
          mkdir build
      - script: |
          git clone https://github.com/oatpp/oatpp
          mkdir -p oatpp/build
        displayName: 'Checkout - oatpp'
        workingDirectory: build
      - script: |
          cmake ..
          sudo make install
        displayName: 'Build - oatpp'
        workingDirectory: build/oatpp/build
      - script: |
          cmake ..
          make
        displayName: 'Build - module'
        workingDirectory: build
      - script: |
          make test ARGS="-V"
        displayName: 'Test'
        workingDirectory: build

  - job: ubuntu_18_04
    displayName: 'Build - Ubuntu 18.04'
    continueOnError: false
    pool:
      vmImage: 'Ubuntu 18.04'
    workspace:
      clean: all
    steps:
      - script: |
          mkdir build
      - script: |
          git clone https://github.com/oatpp/oatpp
          mkdir -p oatpp/build
        displayName: 'Checkout - oatpp'
        workingDirectory: build
      - script: |
          cmake ..
          sudo make install
        displayName: 'Build - oatpp'
        workingDirectory: build/oatpp/build
      - script: |
          cmake ..
          make
        displayName: 'Build - module'
        workingDirectory: build
      - script: |
          make test ARGS="-V"
        displayName: 'Test'
        workingDirectory: build

  - job: ubuntu_20_04
    displayName: 'Build - Ubuntu 20.04'
    continueOnError: false
    pool:
      vmImage: 'Ubuntu 20.04'
    workspace:
      clean: all
    steps:
      - script: |
          mkdir build
      - script: |
          git clone https://github.com/oatpp/oatpp
          mkdir -p oatpp/build
        displayName: 'Checkout - oatpp'
        workingDirectory: build
      - script: |
          cmake ..
          sudo make install
        displayName: 'Build - oatpp'
        workingDirectory: build/oatpp/build
      - script: |
          cmake ..
          make
        displayName: 'Build - module'
        workingDirectory: build
      - script: |
          make test ARGS="-V"
        displayName: 'Test'
        workingDirectory: build

  - job: macOS
    displayName: 'Build - macOS'
    continueOnError: false
    pool:
      vmImage: 'macOS-10.14'
    workspace:
      clean: all
    steps:
      - script: |
          mkdir build
      - script: |
          git clone https://github.com/oatpp/oatpp
          mkdir -p oatpp/build
        displayName: 'Checkout - oatpp'
        workingDirectory: build
      - script: |
          cmake ..
          sudo make install
        displayName: 'Build - oatpp'
        workingDirectory: build/oatpp/build
      - script: |
          cmake ..
          make
        displayName: 'Build - module'
        workingDirectory: build
      - script: |
          make test ARGS="-V"
        displayName: 'Test'
        workingDirectory: build


  - job: windows_vs2017-win2016
    displayName: 'Build - Windows vs2017-win2016'
    continueOnError: false
    pool:
      vmImage: 'vs2017-win2016'
    workspace:
      clean: all
    steps:
      - script: |
          MD build
      - script: |
          git clone https://github.com/oatpp/oatpp
          MD oatpp\build
        displayName: 'Checkout - oatpp'
        workingDirectory: build
      - script: |
          cmake ..
          cmake --build . --target INSTALL
        displayName: 'Build - oatpp'
        workingDirectory: build\oatpp\build

      - script: |
          cmake ..
          cmake --build .
        displayName: 'Build - module'
        workingDirectory: build

      - script: |
          module-tests.exe
        displayName: 'Test'
        workingDirectory: build\test\Debug\

  - job: windows-2019
    displayName: 'Build - Windows windows-2019'
    continueOnError: false
    pool:
      vmImage: 'windows-2019'
    workspace:
      clean: all
    steps:
      - script: |
          MD build
      - script: |
          git clone https://github.com/oatpp/oatpp
          MD oatpp\build
        displayName: 'Checkout - oatpp'
        workingDirectory: build
      - script: |
          cmake ..
          cmake --build . --target INSTALL
        displayName: 'Build - oatpp'
        workingDirectory: build\oatpp\build

      - script: |
          cmake ..
          cmake --build .
        displayName: 'Build - module'
        workingDirectory: build

      - script: |
          module-tests.exe
        displayName: 'Test'
        workingDirectory: build\test\Debug\

